name: main-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v2

      ` name: install python
        uses: 